<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Tanmay" failures="0" tests="8" name="com.deltacapita.test.FinalCalulatorBasketTest" time="0.030" errors="1" timestamp="2025-08-12T19:05:03 IST" skipped="0">
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testMultipleDifferentItems" time="0.002"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testEmptyBasket" time="0.018"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testMelonBuyOneGetOneFreeOddCount" time="0.001"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testSingleApple" time="0.002"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testMixedBasketWithOffers" time="0.001"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testMelonBuyOneGetOneFreeEvenCount" time="0.002"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testLimeThreeForTwo" time="0.002"/>
  <system-out/>
  <testcase classname="com.deltacapita.test.FinalCalulatorBasketTest" name="testUnknownItem" time="0.002">
    <error message="
Method FinalCalulatorBasketTest.testUnknownItem()[pri:0, instance:com.deltacapita.test.FinalCalulatorBasketTest@2e55dd0c] should have thrown an exception of type class java.lang.IllegalArgumentException" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method FinalCalulatorBasketTest.testUnknownItem()[pri:0, instance:com.deltacapita.test.FinalCalulatorBasketTest@2e55dd0c] should have thrown an exception of type class java.lang.IllegalArgumentException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testUnknownItem -->
  <system-out/>
</testsuite> <!-- com.deltacapita.test.FinalCalulatorBasketTest -->
